# Generated by Django 3.0.4 on 2020-05-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_series',
            name='image_series',
        ),
        migrations.RemoveField(
            model_name='image_chapter',
            name='image_chapter_directory',
        ),
        migrations.AddField(
            model_name='book_series',
            name='image_book',
            field=models.ImageField(blank=True, upload_to='mainApp/content'),
        ),
        migrations.AddField(
            model_name='image_chapter',
            name='image_book',
            field=models.ImageField(default=1, upload_to='mainApp/content'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='image_book',
            field=models.ImageField(blank=True, upload_to='mainApp/content'),
        ),
    ]
