# Generated by Django 3.0.4 on 2020-05-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20200512_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_series',
            old_name='image_book',
            new_name='image_series',
        ),
        migrations.RenameField(
            model_name='image_chapter',
            old_name='image_book',
            new_name='Image_chapter',
        ),
        migrations.AlterField(
            model_name='book',
            name='image_book',
            field=models.ImageField(blank=True, upload_to='content'),
        ),
    ]
