# Generated by Django 3.0.4 on 2020-05-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20200512_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_book',
            field=models.ImageField(blank=True, upload_to='static'),
        ),
        migrations.AlterField(
            model_name='book_series',
            name='image_series',
            field=models.ImageField(blank=True, upload_to='static'),
        ),
        migrations.AlterField(
            model_name='image_chapter',
            name='Image_chapter',
            field=models.ImageField(upload_to='static'),
        ),
    ]
